FROM node:16-alpine

# set working directory
WORKDIR /app

# copy package.json to the working directory
COPY package.json /app

# install dependencies
RUN npm i

# copy app files to the working directory
COPY . /app


CMD ["npm", "run", "start"]

# expose port
EXPOSE 3000