FROM ubuntu:latest

# install node.js v 16.20.0
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION v16.20.0
RUN mkdir -p /usr/local/nvm && apt-get update && echo "y" | apt-get install curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH $NODE_PATH:$PATH

# set working directory
WORKDIR /app

# copy package.json to the working directory
COPY package.json /app

# install dependencies
RUN npm i

# copy app files to the working directory
COPY . /app


CMD ["npm", "run", "start"]

# expose port
EXPOSE 3000